export const Style = {
    main: {
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        boxSizing: 'border-box',
        height: '100vh',
        flex: "1 !important",
        flexGrow: "1 !important"
    },
    header: {
        alignItems: 'center',
        background: "#1E2265",
        color: '#fff',
        ml: { xs: 0 },
        width: { xs: "100%" },
        zIndex: 1,
        // minHeight: '78px',
        height: {xs: 'auto', md: '135px'},
        // minHeight: {xs: '135px'},
        display: 'flex',
        gap: '16px',
        px: { xs: 1, sm: 5, md: 6.4 },
        py: {xs: 0, sm: 2.5},
        // pb: {xs: 0, sm: '29px'},
        borderBottom: '17px solid #D6DAFD',
        boxSizing: 'border-box',
        borderRadius: '10px 10px 0 0',
        width: '100%',
        justifyContent: 'space-between'
    },
    trainingPara: {
        // display: 'inline'
        display: '-webkit-box',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        WebkitLineClamp: 2,           // Limit text to 2 lines
        WebkitBoxOrient: 'vertical',   // Control text orientation
        whiteSpace: 'normal',          // Allow line wrapping
        wordBreak: 'break-all',
    },
    trainingHeading: {
        color: '#FFF',
        fontFamily: 'Rubik',
        fontSize: { xs: '22px', sm: '25px', md: '28px' },
        fontWeight: '400',
        lineHeight: '36px',
    },
    trainingName: {
        color: '#FFF',
        fontFamily: 'Rubik',
        fontSize: { xs: '22px', sm: '25px', md: '28px' },
        fontWeight: '600',
        lineHeight: '36px',
        maxHeight: '72px',
        overflow: 'hidden',
        ml: 1.25
    },
    continueButton: {
        display: 'flex',
        width: {xs: '120px', md: '250px'},
        height: '44px',
        padding: '8px',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        color: '#FFF',
        textAlign: 'center',
        fontFamily: 'Rubik',
        fontSize: '16px',
        fontWeight: '500',
        lineHeight: '24px',
        borderRadius: '4px',
        border: '1px solid #3447D4',
        background: '#3447D4',
    },
    stepperMain: {
        display: 'flex',
        padding: {xs: '20px 20px 12px', md: '20px 40px 12px'},
        gap: {xs: 2, md: 4}
    },
    stepperContainer: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: '12px',
        flexGrow: 1,
        flex: 1
    },
    perStepper: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: "33%",
        gap: '6px',
    },
    perStepperChild: (check, color) => ({
        color: check ? color : '#4B4B4B',
        fontFamily: 'Rubik',
        fontSize: '20px',
        fontWeight: check ? "500" : '400',
        opacity: check ? '1' : '0.8'
    }),
    loaderMain: {
        width: '100%',
        height: '4px',
        borderRadius: '10px',
        background: '#EAEAEA',
        mb: 1,
    },
    loaderChild: {
        height: '4px',
        borderRadius: '10px',
        background: '#4156F9',
    },
    contentContainer: {
        display: 'flex',
        flex: 1,
        flexGrow: 1,
        background: '#FBFBFC'
    },
    leftContainer: (isLarge, isFull) => ({
        display: {xs: isFull ? 'flex' : "none", md: 'flex'},
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        width: {xs: isFull ? "100%" : '33%', md: '33%'},
        maxWidth:  {xs: '900px', md: isLarge ? '450px' : "425px"},
        p: '0 20px',
        boxSizing: 'border-box'
    }),
    leftContainerContent: {
        maxWidth:  '330px',
        height: '190px',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center'
    },
    button: {
        width: "100%",
        maxWidth: "320px",
        height: '52px',
        fontSize: '20px',
        mt: 3,
    },
    heading: {
        color: '#1F1F1F',
        fontFamily: 'Rubik',
        fontSize: {xs: '26px', sm: '28px'},
        fontWeight: '500',
    },
    content: {
        color: '#4B4B4B',
        textAlign: 'center',
        fontFamily: 'Rubik',
        fontSize: {xs: '16px', sm: '18px'},
        fontWeight: '400',
        lineHeight: '30px',
        mt: 1
    },
    rightContainer: (isFull) => ({
        display: {xs: isFull ? 'flex' : "none", md: 'flex'},
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        px: {xs: 2, md: 0},
        pr: {xs: 2, md: 3.75, xl: 5},
        flexGrow: 1,
        flex: 1,
        width: {xs: isFull ? "100%" : '66%', md: '66%'}
    }),
    quizContainer: {
        width: '100%',
        maxWidth: '370px',
        m: '28px 34px 0 12px',
        p: '12px 16px',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'start',
        justifyContent: 'start',
        flexGrow: 1,
        flex: 1,
        background: '#FFF',
        boxShadow: '6px 4px 29px rgba(0, 0, 0, 0.05)',
    },
    noQuestion: {
        color: '#1F1F1F',
        fontFamily: 'Rubik',
        fontSize: {xs: '20px', xl: '22px'},
        fontWeight: '500',
        lineHeight: '41px',
        letterSpacing: '-0.2px',
        width: '100%',
        borderBottom: '1px solid #F0F0F0',
        mb: 3
    },
    borderedQuestion: (isActive) => ({
        borderRadius: '7px',
        border: `1px solid ${isActive ? "#3447D4" : "#E0E4EA"}`,
        width: '100%',
        maxWidth: '360px',
        height: '77px',
        display: 'flex',
        p: '12px 40px 12px 10px',
        boxSizing: 'border-box',
        gap: '14px',
        mb: 1.5,
    }),
    question: (isActive) => ({
        color: isActive ? "#1F1F1F" : '#BABABA',
        fontFamily: 'Rubik',
        fontSize: {xs: '16px', xl: '18px'},
        fontWeight: '400',
        lineHeight: '27px',
        letterSpacing: '-0.16px',
        width: 'calc(100% - 35px)',
        // overflow: 'hidden',
        display: '-webkit-box',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        WebkitLineClamp: 2,           // Limit text to 2 lines
        WebkitBoxOrient: 'vertical',   // Control text orientation
        whiteSpace: 'normal',          // Allow line wrapping
        wordBreak: 'break-word'
        // flex: 1,
        // flexGrow: 1,
    }),
    questionNo: {
        width: '29px',
        height: '29px',
        display: "flex",
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: '15px',
        background: '#D7DBF5',
        color: '#1F1F1F',
        fontFamily: 'Rubik',
        fontSize: {xs: '16px', xl: '18px'},
        fontWeight: '500',
        lineHeight: '41px',
        letterSpacing: '-0.16px',
    }
}