const Style = {
  main: {
    display: "flex",
    width: { xs: "100%", md: "45%" },
    maxWidth: { md: "348px", xl: "495px" },
    // height: "271px",
    height: { xs: "271px", xl: "350px" },
    padding: "16px",
    flexDirection: "column",
    alignItems: "center",
    gap: "16px",
    borderRadius: "7px",
    background: "#FFF",
    boxShadow: "0px 4px 39px 0px rgba(81, 69, 159, 0.08)",
  },
  headerContainer: {
    display: "flex",
    width: "100%",
    justifyContent: "space-between",
    px: "2px",
  },
  header: {
    color: "#1F1F1F",
    textAlign: "center",
    fontFamily: "Rubik",
    fontSize: { xs: "18px", xl: "22px" },
    fontWeight: "500",
    lineHeight: "120%",
  },
  mainContainer: {
    display: "flex",
    width: "100%",
    justifyContent: { xs: "center", md: "start", xl: "space-evenly" },
    gap: "20px",
    flexWrap: "no-wrap",
    flexGrow: 1,
  },
  donutHeadingContainer: {
    position: "absolute",
    top: "40%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    textAlign: "center",
  },
  donutPercentage: {
    color: "#1F1F1F",
    textEdge: "cap",
    fontFamily: "Rubik",
    fontSize: { xs: "16px", xl: "26px" },
    fontWeight: "600",
    letterSpacing: "-0.52px",
  },
  donutCompleted: {
    color: "#1F1F1F",
    textEdge: "cap",
    fontFamily: "Rubik",
    fontSize: { xs: "18px", xl: "20px" },
    fontWeight: "400",
  },
  labelContainer: {
    display: "flex",
    alignItems: "center",
    gap: 1,
    minWidth: "94px",
    mt: 1.5,
  },
  color: {
    width: { xs: "8px", xl: "11px" },
    height: { xs: "8px", xl: "11px" },
    borderRadius: { xs: "8px", xl: "11px" },
  },
  label: {
    color: "#4B4B4B",
    fontFamily: "Rubik",
    fontSize: { xs: "10px", xl: "18px" },
    fontWeight: "400",
    lineHeight: "130%",
  },
  labelNo: {
    color: "#1F1F1F",
    textAlign: "start",
    fontFamily: "Rubik",
    fontSize: { xs: "14px", xl: "22px" },
    fontWeight: "400",
    lineHeight: "120%",
    mt: 0.75,
    pl: 1.75,
  },
};
export { Style };
