import { COLORS, IMAGES } from "../../theme";

export const Style = {
  main: {
    width: { xs: "100%", md: "65.7%" },
    height: { xs: "40%", md: "100%" },
    maxWidth: "820px",
    mt: { xs: "20px", sm: "20px", md: 0 },
    backgroundColor: "white",
    boxSizing: "border-box",
    display: { xs: "flex", md: "flex" },
    flexWrap: "wrap",
    overflow: "visible",
    zIndex: 1,
  },
  content: {
    // background: "black",
    width: { xs: "100%", md: "100%" },
    height: { xs: "100%", md: "100%" },
    backgroundRepeat: "no-repeat",
    borderRadius: { xs: "4px", md: "22px" },
    backgroundImage: {
      xs: `url(${IMAGES.mobileview})`,
      sm: `url(${IMAGES.leftbanner})`,
      lg: `url(${IMAGES.leftbanner})`,
      xl: `url(${IMAGES.leftbanner})`,
    },
    backgroundSize: { 
      xs: "cover",
      sm: "cover",
      md: "cover" 
    },
    backgroundPosition: "center",
    boxShadow: {
      xs: "",
      sm: "0px 14px 60px 0px rgba(0, 0, 0, 0.25)",
      lg: "0px 14px 60px 0px rgba(0, 0, 0, 0.25)",
      md: "0px 14px 60px 0px rgba(0, 0, 0, 0.25)",
      xl: "0px 14px 60px 0px rgba(0, 0, 0, 0.25)",
    },
    backgroundColor: {
      xs: "",
      sm: "#050505",
      lg: "#050505",
      xl: "#050505",
    },
    maxHeight: "780px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    color: COLORS.white,
    p: "-10px",
  },
  welcomeHeading: {
    fontFamily: "serif",
    fontWeight: 900,
    fontSize: "40px",
    lineHeight: 1.5,
    letterSpacing: "2px",
  },
  appName: {
    fontFamily: "serif",
    fontWeight: 600,
    fontSize: "28px",
    lineHeight: 1.5,
    letterSpacing: "2px",
  },
  slogan: {
    fontFamily: "serif",
    fontWeight: 600,
    fontSize: "28px",
    lineHeight: 1.5,
    letterSpacing: "2px",
  },
};
