export const Style = {
  main: (isDrawer) => ({
    display: "flex",
    padding: { xs: "14px", sm: "20px" },
    boxSizing: "border-box",
    gap: "20px",
    background: "#EBF5F9",
    flexWrap: "wrap",
    width: "100%",
    height: "fit-content",
  }),
  tittleContainer: {
    width: "100%",
    display: "flex",
    px: 2,
    justifyContent: "space-between",
    alignItems: "center",
    background: "#12385D",
    height: "52px",
    color: "#fff",
  },
  menuIcon: { fontSize: 24, cursor: "pointer", mr: "5px" },
  tittle: {
    fontSize: "28px",
    fontFamily: "Literata",
    width: "100%",
    display: "flex",
    justifyContent: "center",
  },
  tableContainer: {
    background: "white",
    boxSizing: "border-box",
    display: "flex",
    width: "100%",
    minWidth: "200px",
    minHeight: "260px",
    height: {
      xs: "calc( 100vh - 120px )",
      md: "calc( 100vh - 520px )",
    },
    "& .MuiDataGrid-scrollbar": {
      "&::-webkit-scrollbar": {
        width: "5px",
        height: "5px",
      },
      "::-webkit-scrollbar-thumb": {
        background: "#12385D",
        borderRadius: "6px",
      },
    },
  },
  tableBody: { width: "100%", minWidth: "223px" },
  tableRow: {
    "&:last-child td, &:last-child th": {
      border: 0,
      width: "100%",
    },
  },
  tableCell: { width: "40px !important" },
  deleteIcon: (isDeleteDisable) => ({
    cursor: isDeleteDisable ? "pointer" : "not-allowed",
    fill: isDeleteDisable ? "white" : "rgba(255, 255, 255, 0.3)",
  }),
  course: (isDashboard, isRed) => ({
    height: "50px",
    color: isRed ? "#D92D20" : "#1F1F1F",
    fontFamily: "Rubik",
    fontSize: "16px",
    fontWeight: "400",
    letterSpacing: "0.5px",
    display: "flex",
    alignItems: "center !important",
    pl: !isDashboard && "22px",
    pt: "5px",
  }),
  circularProgressbar: (isgreen) => ({
    rotation: 0,
    pathColor: isgreen ? "#4FA97C" : "#D92D20",
    trailColor: "#F3F3F2",
    backgroundColor: "#F3F3F2",
    textColor: "#1F1F1F",
    fontWeight: "700",
    paddingTop: "15px !important",
  }),
};
